services:
  backend:
    build: .
    container_name: electricity-backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - electricity-network
    depends_on:
      - db
      - migrate
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    networks:
      - electricity-network

  migrate:
    image: node:18-alpine
    container_name: electricity-migrate
    command: sh -c "npm install && npx prisma migrate resolve --applied 0_init && npx prisma migrate deploy"
    working_dir: /app
    volumes:
      - .:/app
      - ./prisma:/app/prisma # Explicitly mount the prisma directory
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - electricity-network
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
    networks:
      - electricity-network

networks:
  electricity-network:
    driver: bridge
